services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    env_file:
      - .env.local
    depends_on:
      - redis
      - mongo
    ports:
      - "${APP_PORT}:${APP_PORT}"

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "no"]
    env_file:
      - .env.local
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  mongo:
    image: mongo:7
    restart: always
    env_file:
      - .env.local
    ports:
      - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    command: ["--port", "${MONGODB_PORT}"]